name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: 127348941
          revision: "${{ github.ref }}-${{ github.sha }}"

          changelog: "See https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md for details"
          description: "Aabed's testing mark"
          user: "${{ github.actor }}"